### ISSUE TITLE
can’t edit Custom start G-Code panel

### ISSUE THREAD

**Issue by uomou** [fellesverkstedet/Bark-beetle-parametric-toolpaths#66]
probably a silly one, but somehow I can't edit that panel?

**Comment by Siemenc** [comment]
Are you trying to edit Panel A or panel B from my image below?
![image](https://user-images.githubusercontent.com/10272127/83907668-1b9d0700-a766-11ea-9f4b-745afbbae147.png)

Panel B cannot be changed unless you disconnect the input coming from the component. Panel A can be changed, but I'm not sure how that is going to affect the start code so that it matches your machine, so you might be better off disconnecting the input form panel B and copying the startcode to your machine.

**Comment by uomou** [comment]
SOLVED
was trying to edit B :-)
