### ISSUE TITLE
Make a better trochoidal milling entry

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#71]
I never used trochoidal milling but have been curious about it. It looks to me like the entry seems a bit harsh on the milling bit? Below is a screenshot of cutting at 5 mm depth. I'd expect the milling bit to make a spiral at the beginning before starting to cut around, whereas it seems like it moves in rather quickly

![image](https://user-images.githubusercontent.com/10272127/93613108-b4335c00-f9d0-11ea-8294-3ce232e9537f.png)

Also, perhaps we should make this setting as a bit more of an advanced setting or have some warning when using this or rename it. I think it's quite tempting to click on this when opening bark beetle for the first time thinking "Cool, high speed machining! Sounds great!" Whereas in wood for instance you get a higher speed of machining (as in, finish the piece, not the actual speed of the milling bit perhaps) by just cutting with a profile pass.

**Comment by JensDyvik** [comment]
I just fixed this in "Bark beetle 1.02 beta 4 - CNC milling - Rhino6.gh" published here: https://github.com/fellesverkstedet/Bark-beetle-parametric-toolpaths/tree/master/Development%20files

The error came from the this component changing input order in grasshopper for rhino6 from rhino5:
![angle-fix-for-ramp-entry](https://user-images.githubusercontent.com/6598148/113583239-ac17d280-9629-11eb-8584-93f601ce8422.PNG)

I agree that high speed machining is an advanced setting _(and quite rarely used)_, so I moved the it to advanced 2D settings. This makes our main setting list shorter and less intimidating :)
![new-location-setting](https://user-images.githubusercontent.com/6598148/113584671-75db5280-962b-11eb-8c43-36fcfdfaf3f8.PNG)

I originally made the helix type an experimental variable diameter helix, which turned out to not be optimal:
![variable diameter helix](https://user-images.githubusercontent.com/6598148/113583459-f731e580-9629-11eb-8432-888e4e9e2897.PNG)

I started work on making a classic constant diameter helix instead, but my concentration failed me. So for now I changed the default width factor of the trochoidal path from 2.3 to 2.01, which makes a near straight helix:
![variable diameter helix - temp fix](https://user-images.githubusercontent.com/6598148/113583677-40823500-962a-11eb-9c47-55518d5f3417.PNG)
